name: ðŸ‹ï¸ Deploy cloud-stress (US West)

on:
  workflow_dispatch: # Manual trigger fallback
  push:
    branches:
      - cloud/cloud-scaling
    paths:
      - "cloud/**"
      - ".github/workflows/porter-stress.yml"
jobs:
  us-west:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: Deploy cloud-stress to US West
        timeout-minutes: 30
        run: exec porter apply -f ./cloud/porter-stress.yaml
        env:
          PORTER_APP_NAME: cloud-stress
          PORTER_NAMESPACE: stress
          NODE_ENV: stress
          PORTER_CLUSTER: "4965"
          PORTER_DEPLOYMENT_TARGET_ID: 540690ee-b1d7-4a5e-80e9-683d11001c75
          PORTER_HOST: https://dashboard.porter.run
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_PROJECT: "15081"
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4965 }}
